[build]
  command = "pnpm run build"
  publish = "out"

[build.environment]
  PNPM_VERSION = "9.12.3"
  NODE_VERSION = "20"

# Removed [[plugins]] section - @netlify/plugin-nextjs conflicts with static export